### ISSUE TITLE
3D human pose estimation

### ISSUE THREAD

**Issue by sulei1998** [yz-cnsdqz/PSI-release#4]
Hello! Nice work! But i have a question, when i read your paper, i notice that you said your work can improve 3D pose estimation from monocular images. **So i want to know how to combine your work with the prox, is there any codes?** I have tested the [PROX] (https://github.com/MohameHassan/prox)  before and i find that prox fit a image cost lots of time.  **So I'm curious if your method can increase the running speed?**

Thanks a lot!

**Comment by yz-cnsdqz** [comment]
Many thanks for interests. Answers are below:

> Hello! Nice work! But i have a question, when i read your paper, i notice that you said your work can improve 3D pose estimation from monocular images. **So i want to know how to combine your work with the prox, is there any codes?** 

The method is already mentioned in the manuscript. The code is not provided here, since the modification is rather simple: (1) Get the scene depth and semantics. (2) Generate multiple bodies using our model (S1 or S2), and compute their average. (3) Replace the Vposer term in the PROX fitting loss by that calculated average. Perhaps you need adjust the hyper-parameters. (4) Run the modified PROX fitting as usual.

>I have tested the [PROX] (https://github.com/MohameHassan/prox) before and i find that prox fit a image cost lots of time. **So I'm curious if your method can increase the running speed?**

no. 

> 
> Thanks a lot!

**Comment by sulei1998** [comment]
Thanks for the kind reply!
