### ISSUE TITLE
how to generate semantic segmentations for a 3D scene.

### ISSUE THREAD

**Issue by ZZWENG** [yz-cnsdqz/PSI-release#7]
Hi, thank you for the great work! 

I was wondering how you generated semantic segmentations in the camera views like those in snapshot_for_testing (data['seg']). I am trying to do that for all the 3D scenes in PROX by rendering the vertices in scene_semantics. However, I am not able to get it to work using the rendering and perspective cameras in pytorch3D. 

Could you share your method of generating those?

**Comment by yz-cnsdqz** [comment]
> Hi, thank you for the great work!
> 
> I was wondering how you generated semantic segmentations in the camera views like those in snapshot_for_testing (data['seg']). I am trying to do that for all the 3D scenes in PROX by rendering the vertices in scene_semantics. However, I am not able to get it to work using the rendering and perspective cameras in pytorch3D.
> 
> Could you share your method of generating those?

Thanks for your interests! I used open3d to render rather than pytorch3d, but I think the principle should be the same. 

The mesh vertex color corresponds to the semantics, but it is arranged within [0,1] if I remember correctly.  Also, you need to divide the mesh verts color by 5.  For details you could check the code and instructions. Hope it is helpful.

**Comment by ZZWENG** [comment]
Thank you! I will check out the `utils_prox_snapshots_realcam.py` file that seems to do it.
